"""Generate each harness's agent files from the roles file, so every adapter runs the same roles.

Claude Code: .claude/agents/<role>.md (model, effort, tools, the role's versioned prompt).
Codex:       .codex/profiles/factory-<role>.config.toml (model, reasoning effort, sandbox); the codex
             adapter's install.sh links them into $CODEX_HOME so `codex -p factory-<role>` uses them.
Never edit a generated file: change factory.toml or the prompt file, then run `factory agents`.
"""
import hashlib
from pathlib import Path

DESCRIPTIONS = {
    "chief-of-staff": "The continuous chief-of-staff session: cuts, splits, decides, writes the retro, reports to the human. Never picks models or starts roles itself.",
    "builder": "Builds one factory unit from its brief. Started only by the clock with its pinned model; never start it from a session.",
    "reviewer": "Inspector Grumble: independent review of one built unit in a fresh session. Started only by the clock; never start it from a session.",
    "researcher": "Read-only research before any work that adopts an outside tool; writes the reviewed work spec.",
    "summarizer": "Short plain summaries of factory records; changes no number.",
}


def header(role, prompt_path):
    sha = hashlib.sha256(Path(prompt_path).read_bytes()).hexdigest()[:12]
    return (f"Generated by the factory from the roles file (role {role}, prompt {Path(prompt_path).name}, "
            f"sha {sha}). Do not edit: change factory.toml or the prompt, then run: factory agents")


def claude_agent(name, role, prompt_path):
    tools = []
    for tool in role.get("tools", []):
        base = tool.split("(", 1)[0]
        if base not in tools:
            tools.append(base)
    lines = ["---", f"name: {name}", f"description: {DESCRIPTIONS[name]}", f"model: {role['model']}",
             f"effort: {role['effort']}"]
    if tools:
        lines.append(f"tools: {', '.join(tools)}")
    return "\n".join(lines + ["---", "", f"<!-- {header(name, prompt_path)} -->", "",
                              Path(prompt_path).read_text().rstrip(), ""])


def codex_profile(name, role, prompt_path):
    sandbox = (role.get("tools") or ["workspace-write"])[0]
    return (f"# {header(name, prompt_path)}\nmodel = \"{role['model']}\"\n"
            f"model_reasoning_effort = \"{role['effort']}\"\nsandbox_mode = \"{sandbox}\"\n")


def generate(roles, prompt_root, out_root):
    """Write the agent files for every role whose tool has them. Returns the written paths."""
    written = []
    for name, role in roles.items():
        prompt = Path(prompt_root) / role["prompt"]
        if role["tool"] == "claude":
            path, text = Path(out_root) / ".claude/agents" / f"{name}.md", claude_agent(name, role, prompt)
        elif role["tool"] == "codex":
            path, text = Path(out_root) / ".codex/profiles" / f"factory-{name}.config.toml", codex_profile(name, role, prompt)
        else:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        written.append(str(path))
    return written


def crew_agent_files(crew, roles, prompt_root, out_root):
    """One source (crew.toml + prompts) -> Claude agent files, Codex profiles and a tool-neutral AGENT.md."""
    written = []
    for name, agent in crew["agents"].items():
        if name == "inspector-grumble":
            continue  # it is the reviewer role; its files come from the roles file
        role = roles[agent["uses_role"]]
        prompt = Path(prompt_root) / agent["prompt"]
        triggers = [f"{t['event']} ({t['when']})" for t in crew["triggers"] if t["agent"] == name]
        pinned = {**role, "effort": agent["effort"], "tools": agent["tools"] if role["tool"] == "claude" else [agent["sandbox"]]}
        DESCRIPTIONS.setdefault(name, f"Crew agent {name}. Started only by code on: {', '.join(triggers)}. Never start it from a session.")
        neutral = Path(out_root) / "crew" / name / "AGENT.md"
        neutral.parent.mkdir(parents=True, exist_ok=True)
        neutral.write_text(f"<!-- {header(name, prompt)} -->\n# {name}\n\nStarted only by code on: {', '.join(triggers)}.\n"
                           f"Model: {role['tool']}:{role['model']} (the {agent['uses_role']} role), effort {agent['effort']}. "
                           f"Answer form: {agent['form']}, checked by factory/crew.py.\n\n{prompt.read_text()}")
        written.append(str(neutral))
        if role["tool"] == "claude":
            path, text = Path(out_root) / ".claude/agents" / f"{name}.md", claude_agent(name, pinned, prompt)
        elif role["tool"] == "codex":
            path, text = Path(out_root) / ".codex/profiles" / f"factory-{name}.config.toml", codex_profile(name, pinned, prompt)
        else:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        written.append(str(path))
    return written


def generate_all(project):
    """Every agent file of a project, from its factory.toml, factory/crew.toml and .ai/prompts."""
    import tomllib
    project = Path(project)
    roles = tomllib.loads((project / "factory.toml").read_text())["roles"]
    crew = tomllib.loads((project / "factory/crew.toml").read_text())
    return generate(roles, project, project) + crew_agent_files(crew, roles, project, project)
